apiVersion: v1
kind: Service
metadata:
  name: schema-registry-svc
  namespace: kafka
  labels:
    app: schema-registry-svc
spec:
  ports:
    - name: schema-registry
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: schema-registry-svc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: schema-registry-app
  namespace: kafka
  name: schema-registry-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry-app
  template:
    metadata:
      labels:
        app: schema-registry-app
    spec:
      enableServiceLinks: false
      containers:
        - env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry-svc
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
            - name: SCHEMA_REGISTRY_MASTER_ELIGIBILITY
              value: "true"
            - name: SCHEMA_REGISTRY_DEBUG
              value: "true"
            - name: SCHEMA_REGISTRY_HEAP_OPTS
              value: -Xms512M -Xmx2G
            - name: SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID
              value: cp-schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
              value: _schemas
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://10.101.34.60:9092
          name: schema-registry-app
          image: confluentinc/cp-schema-registry:6.0.1
          ports:
            - containerPort: 8081
              protocol: TCP