app_name: kafka-transactions

connections:
  - config : !Kafka
      broker: localhost:19092
      schema_registry_url: http://localhost:18081
    name: kafka_store

sources:
  - name: transactions
    table_name: transactions
    connection: kafka_store

sql: |
  SELECT
    t.id,
    t.customer_id,
    t.amount,
    t.location,
    t.provider
  INTO tout
  FROM transactions t;

endpoints:
  - name: tout
    path: /tout
    table_name: tout
