app_name: simple-pg-sample
connections:
  - name: pagila_conn
    config: !Postgres
      user: postgres
      password: postgres
      host: ec2-18-141-13-58.ap-southeast-1.compute.amazonaws.com
      port: 5433
      database: pagila

sources:
  - name: actors
    table_name: actor
    connection: pagila_conn
  - name: films
    table_name: film
    connection: pagila_conn
    columns:
      - film_id
      - title

endpoints:
  - name: actors
    path: /actors
    table_name: actors

  - name: films
    path: /films
    table_name: films
