app_name: local-application
connections:
  - config: !LocalStorage
      details:
        path: 2-active-data
      tables:
        - !Table
          name: customers
          config: !Parquet
            path: customers
            extension: .parquet
        - !Table
          name: orders
          config: !Parquet
            path: orders
            extension: .parquet
        - !Table
          name: order_items
          config: !Parquet
            path: order_items
            extension: .parquet
        - !Table
          name: products
          config: !Parquet
            path: products
            extension: .parquet
    name: delta

sql: |
  select c.customer_id, c.name, c.email,  o.order_id, o.order_date, o.total_amount, COUNT(*)
  into customer_orders 
  from customers c
  inner join orders o on c.customer_id = o.customer_id
  join order_items i on o.order_id = i.order_id
  join products p on i.product_id = p.product_id
  group by c.customer_id, c.name, c.email, o.order_id, o.order_date, o.total_amount

endpoints:
  - name: customers
    path: /customers
    table_name: customers
    index:
      primary_key:
        - customer_id

  - name: orders
    path: /orders
    table_name: orders
    index:
      primary_key:
        - order_id

  - name: customer_orders_cache
    path: /customer_orders
    table_name: customer_orders

telemetry:
  metrics: !Prometheus
